env:
  - CABALVER=1.22 GHCVER=7.10.1

before_install:
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq cabal-install-$CABALVER ghc-$GHCVER
  - export PATH="/opt/cabal/$CABALVER/bin:/opt/ghc/$GHCVER/bin:$PATH"

before_script:
  - cabal --version
  - cabal update
  - ghc --version
  - ghc-pkg list

script:
  - cabal install
  - cabal sdist

after_script:
  - ghc-pkg list
