name: "Build package"
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: markus1189
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix build
